[2023-03-29 16:50:33,188] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: postgres_22222222222.log_error 2023-03-29T16:50:31.554255+00:00 [queued]>
[2023-03-29 16:50:33,204] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: postgres_22222222222.log_error 2023-03-29T16:50:31.554255+00:00 [queued]>
[2023-03-29 16:50:33,206] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 16:50:33,208] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2023-03-29 16:50:33,209] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 16:50:33,237] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): log_error> on 2023-03-29T16:50:31.554255+00:00
[2023-03-29 16:50:33,251] {standard_task_runner.py:52} INFO - Started process 28101 to run task
[2023-03-29 16:50:33,268] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'postgres_22222222222', 'log_error', '2023-03-29T16:50:31.554255+00:00', '--job-id', '429', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmpp97a4i0n', '--error-file', '/tmp/tmpq6flnd6_']
[2023-03-29 16:50:33,271] {standard_task_runner.py:77} INFO - Job 429: Subtask log_error
[2023-03-29 16:50:33,355] {logging_mixin.py:109} INFO - Running <TaskInstance: postgres_22222222222.log_error 2023-03-29T16:50:31.554255+00:00 [running]> on host 0bc3da97cebb
[2023-03-29 16:50:33,420] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgres_22222222222
AIRFLOW_CTX_TASK_ID=log_error
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T16:50:31.554255+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-29T16:50:31.554255+00:00
[2023-03-29 16:50:33,456] {python.py:151} INFO - Done. Returned value was: None
[2023-03-29 16:50:33,470] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=postgres_22222222222, task_id=log_error, execution_date=20230329T165031, start_date=20230329T165033, end_date=20230329T165033
[2023-03-29 16:50:33,528] {local_task_job.py:151} INFO - Task exited with return code 0
[2023-03-29 16:50:33,569] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
