[2023-03-29 16:15:44,960] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: postgres_22222222222.log_error 2023-03-29T16:15:43.429547+00:00 [queued]>
[2023-03-29 16:15:44,978] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: postgres_22222222222.log_error 2023-03-29T16:15:43.429547+00:00 [queued]>
[2023-03-29 16:15:44,980] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 16:15:44,981] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2023-03-29 16:15:44,982] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 16:15:45,011] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): log_error> on 2023-03-29T16:15:43.429547+00:00
[2023-03-29 16:15:45,022] {standard_task_runner.py:52} INFO - Started process 26274 to run task
[2023-03-29 16:15:45,038] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'postgres_22222222222', 'log_error', '2023-03-29T16:15:43.429547+00:00', '--job-id', '297', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmpiepwv82g', '--error-file', '/tmp/tmprur5xpps']
[2023-03-29 16:15:45,041] {standard_task_runner.py:77} INFO - Job 297: Subtask log_error
[2023-03-29 16:15:45,109] {logging_mixin.py:109} INFO - Running <TaskInstance: postgres_22222222222.log_error 2023-03-29T16:15:43.429547+00:00 [running]> on host 0bc3da97cebb
[2023-03-29 16:15:45,181] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgres_22222222222
AIRFLOW_CTX_TASK_ID=log_error
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T16:15:43.429547+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-29T16:15:43.429547+00:00
[2023-03-29 16:15:45,183] {ETL.py:67} ERROR - task is NOT completed
[2023-03-29 16:15:45,202] {python.py:151} INFO - Done. Returned value was: None
[2023-03-29 16:15:45,224] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=postgres_22222222222, task_id=log_error, execution_date=20230329T161543, start_date=20230329T161544, end_date=20230329T161545
[2023-03-29 16:15:45,257] {local_task_job.py:151} INFO - Task exited with return code 0
[2023-03-29 16:15:45,285] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
