[2023-03-29 16:17:36,954] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: postgres_22222222222.log_error 2023-03-29T16:17:34.561041+00:00 [queued]>
[2023-03-29 16:17:36,980] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: postgres_22222222222.log_error 2023-03-29T16:17:34.561041+00:00 [queued]>
[2023-03-29 16:17:36,981] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 16:17:36,983] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2023-03-29 16:17:36,985] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 16:17:37,011] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): log_error> on 2023-03-29T16:17:34.561041+00:00
[2023-03-29 16:17:37,027] {standard_task_runner.py:52} INFO - Started process 26382 to run task
[2023-03-29 16:17:37,056] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'postgres_22222222222', 'log_error', '2023-03-29T16:17:34.561041+00:00', '--job-id', '309', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmpx0u2atl4', '--error-file', '/tmp/tmpvbchrx_4']
[2023-03-29 16:17:37,058] {standard_task_runner.py:77} INFO - Job 309: Subtask log_error
[2023-03-29 16:17:37,210] {logging_mixin.py:109} INFO - Running <TaskInstance: postgres_22222222222.log_error 2023-03-29T16:17:34.561041+00:00 [running]> on host 0bc3da97cebb
[2023-03-29 16:17:37,335] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgres_22222222222
AIRFLOW_CTX_TASK_ID=log_error
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T16:17:34.561041+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-29T16:17:34.561041+00:00
[2023-03-29 16:17:37,340] {ETL.py:67} ERROR - task is NOT completed
[2023-03-29 16:17:37,369] {python.py:151} INFO - Done. Returned value was: None
[2023-03-29 16:17:37,425] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=postgres_22222222222, task_id=log_error, execution_date=20230329T161734, start_date=20230329T161736, end_date=20230329T161737
[2023-03-29 16:17:37,509] {local_task_job.py:151} INFO - Task exited with return code 0
[2023-03-29 16:17:37,554] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
