[2023-03-28 18:06:45,917] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: postgres_etl_dag_radb_to_mmr.etl_from_radb_to_mrrdimcustimer 2023-03-26T00:00:00+00:00 [queued]>
[2023-03-28 18:06:46,214] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: postgres_etl_dag_radb_to_mmr.etl_from_radb_to_mrrdimcustimer 2023-03-26T00:00:00+00:00 [queued]>
[2023-03-28 18:06:46,217] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2023-03-28 18:06:46,219] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2023-03-28 18:06:46,220] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2023-03-28 18:06:46,517] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): etl_from_radb_to_mrrdimcustimer> on 2023-03-26T00:00:00+00:00
[2023-03-28 18:06:47,089] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'postgres_etl_dag_radb_to_mmr', 'etl_from_radb_to_mrrdimcustimer', '2023-03-26T00:00:00+00:00', '--job-id', '26', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/inovus_etl_radb_mrr_stg_dwh.py', '--cfg-path', '/tmp/tmp2xloz0dj', '--error-file', '/tmp/tmpdhimcik6']
[2023-03-28 18:06:47,128] {standard_task_runner.py:77} INFO - Job 26: Subtask etl_from_radb_to_mrrdimcustimer
[2023-03-28 18:06:47,015] {standard_task_runner.py:52} INFO - Started process 7690 to run task
[2023-03-28 18:06:47,773] {logging_mixin.py:109} INFO - Running <TaskInstance: postgres_etl_dag_radb_to_mmr.etl_from_radb_to_mrrdimcustimer 2023-03-26T00:00:00+00:00 [running]> on host 0bc3da97cebb
[2023-03-28 18:06:48,380] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgres_etl_dag_radb_to_mmr
AIRFLOW_CTX_TASK_ID=etl_from_radb_to_mrrdimcustimer
AIRFLOW_CTX_EXECUTION_DATE=2023-03-26T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-26T00:00:00+00:00
[2023-03-28 18:06:56,692] {taskinstance.py:1463} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1165, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1283, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1313, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/inovus_etl_radb_mrr_stg_dwh.py", line 48, in etl_postgres_mmr_dimcustimer
    cur_p.execute("select * from ra_inovus.custimer;") # 1
psycopg2.errors.UndefinedTable: relation "ra_inovus.custimer" does not exist
LINE 1: select * from ra_inovus.custimer;
                      ^

[2023-03-28 18:06:57,126] {taskinstance.py:1513} INFO - Marking task as FAILED. dag_id=postgres_etl_dag_radb_to_mmr, task_id=etl_from_radb_to_mrrdimcustimer, execution_date=20230326T000000, start_date=20230328T180645, end_date=20230328T180657
[2023-03-28 18:06:58,773] {local_task_job.py:151} INFO - Task exited with return code 1
[2023-03-28 18:06:59,051] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
